/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo;

import javax.swing.ImageIcon;

/**
 *
 * @author Jean Luca
 */
public class ViewJogo extends javax.swing.JFrame {

    /**
     * Creates new form ViewJogo
     */
    public ViewJogo() {
        initComponents();
        jButtonJogar.setEnabled(false);
        jLabelResultado.setEnabled(false);
        jLabelMensagemResultado.setEnabled(false);
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSuasOpcoes = new javax.swing.JLabel();
        jLabelOpcaoPapel = new javax.swing.JLabel();
        jLabelNomeJogador = new javax.swing.JLabel();
        jLabelNomeComputador = new javax.swing.JLabel();
        jLabelOpcaoPedra = new javax.swing.JLabel();
        jLabelOpcaoTesoura = new javax.swing.JLabel();
        jLabelJogador = new javax.swing.JLabel();
        jLabelVersus = new javax.swing.JLabel();
        jLabelComputador = new javax.swing.JLabel();
        jButtonJogar = new javax.swing.JButton();
        jLabelResultado = new javax.swing.JLabel();
        jLabelMensagemResultado = new javax.swing.JLabel();
        jButtonRanking = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelSuasOpcoes.setText("Suas opções:");

        jLabelOpcaoPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_96px_1.png"))); // NOI18N
        jLabelOpcaoPapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOpcaoPapelMouseClicked(evt);
            }
        });

        jLabelNomeJogador.setText("Você escolheu:");

        jLabelNomeComputador.setText("Computador");

        jLabelOpcaoPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_Rock_96px_1.png"))); // NOI18N
        jLabelOpcaoPedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOpcaoPedraMouseClicked(evt);
            }
        });

        jLabelOpcaoTesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_Scissors_96px.png"))); // NOI18N
        jLabelOpcaoTesoura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOpcaoTesouraMouseClicked(evt);
            }
        });

        jLabelJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/interrogacao.png"))); // NOI18N

        jLabelVersus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/versus.png"))); // NOI18N

        jLabelComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/interrogacao.png"))); // NOI18N

        jButtonJogar.setText("Jogar");
        jButtonJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJogarActionPerformed(evt);
            }
        });

        jLabelResultado.setText("Resultado:");

        jButtonRanking.setText("Ranking");
        jButtonRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRankingActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabelNomeJogador)
                                .addGap(208, 208, 208)
                                .addComponent(jLabelNomeComputador))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabelJogador)
                                .addGap(48, 48, 48)
                                .addComponent(jLabelVersus)
                                .addGap(48, 48, 48)
                                .addComponent(jLabelComputador))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jButtonJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSuasOpcoes)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelOpcaoPedra)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelOpcaoPapel)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelOpcaoTesoura)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelResultado)
                            .addComponent(jLabelMensagemResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelSuasOpcoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOpcaoPapel)
                            .addComponent(jLabelOpcaoTesoura)
                            .addComponent(jLabelOpcaoPedra)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelResultado)
                        .addGap(21, 21, 21)
                        .addComponent(jLabelMensagemResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeJogador)
                    .addComponent(jLabelNomeComputador))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJogador)
                    .addComponent(jLabelVersus)
                    .addComponent(jLabelComputador))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButtonJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRanking)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar)
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int escolhaJogador = 3;
    private void jLabelOpcaoPedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpcaoPedraMouseClicked
        jLabelJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_Rock_100px.png")));
        jLabelComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/jokenpo.gif")));
        escolhaJogador = 0;
        jButtonJogar.setEnabled(true);
    }//GEN-LAST:event_jLabelOpcaoPedraMouseClicked

    private void jLabelOpcaoPapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpcaoPapelMouseClicked
        jLabelJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_100px.png")));
        jLabelComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/jokenpo.gif")));
        escolhaJogador = 1;
        jButtonJogar.setEnabled(true);
    }//GEN-LAST:event_jLabelOpcaoPapelMouseClicked

    private void jLabelOpcaoTesouraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpcaoTesouraMouseClicked
        jLabelJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_Scissors_100px.png")));
        jLabelComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/jokenpo.gif")));
        escolhaJogador = 2;
        jButtonJogar.setEnabled(true);
    }//GEN-LAST:event_jLabelOpcaoTesouraMouseClicked

    private void jButtonJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJogarActionPerformed
        String mensagem = "";
        
        IniciarConfronto iniciarConfronto = new IniciarConfronto();
        JogadorDAO jogadorDAO = new JogadorDAO();
        Jogador jogador = new Jogador();
        
        
        switch (escolhaJogador)
        {
            case 0:
                jLabelMensagemResultado.setText(iniciarConfronto.Jogar(0));
                mensagem = jLabelMensagemResultado.getText();
                switch (iniciarConfronto.OpcaoComputador())
                {
                    case 0:
                        jLabelComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_Rock_100px.png")));
                        
                        break;
                        
                    case 1:
                        jLabelComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_100px.png")));
                        break;
                        
                    case 2:
                        jLabelComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_Scissors_100px.png")));
                        break;
                        
                    default:
                        System.out.println("Opção inválida");
                }
                break;
                
            case 1:
                jLabelMensagemResultado.setText(iniciarConfronto.Jogar(1));
                mensagem = jLabelMensagemResultado.getText();
                switch (iniciarConfronto.OpcaoComputador())
                {
                    case 0:
                        jLabelComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_Rock_100px.png")));
                        break;
                        
                    case 1:
                        jLabelComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_100px.png")));
                        break;
                        
                    case 2:
                        jLabelComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_Scissors_100px.png")));
                        break;
                        
                    default:
                        System.out.println("Opção inválida");
                }
                break;
                
            case 2:
                jLabelMensagemResultado.setText(iniciarConfronto.Jogar(2));
                mensagem = jLabelMensagemResultado.getText();
                switch (iniciarConfronto.OpcaoComputador())
                {
                    case 0:
                        jLabelComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_Rock_100px.png")));
                        break;
                        
                    case 1:
                        jLabelComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_100px.png")));
                        break;
                        
                    case 2:
                        jLabelComputador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Hand_Scissors_100px.png")));
                        break;
                        
                    default:
                        System.out.println("Opção inválida");
                }   
                break;
                
            default:
                System.out.println("Valor informado errado");
                
        }
        
        //jLabelMensagemResultado.setText(mensagem);
        System.out.println(jogador.getNickname());
        jogadorDAO.update(jogador, mensagem);
        jLabelResultado.setEnabled(true);
        jLabelMensagemResultado.setEnabled(true);
        
    }//GEN-LAST:event_jButtonJogarActionPerformed

    private void jButtonRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRankingActionPerformed
        new ViewRanking().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRankingActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
         new ViewInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewJogo().setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButtonJogar;
    private javax.swing.JButton jButtonRanking;
    private javax.swing.JLabel jLabelComputador;
    private javax.swing.JLabel jLabelJogador;
    private javax.swing.JLabel jLabelMensagemResultado;
    private javax.swing.JLabel jLabelNomeComputador;
    private javax.swing.JLabel jLabelNomeJogador;
    private javax.swing.JLabel jLabelOpcaoPapel;
    private javax.swing.JLabel jLabelOpcaoPedra;
    private javax.swing.JLabel jLabelOpcaoTesoura;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelSuasOpcoes;
    private javax.swing.JLabel jLabelVersus;
    // End of variables declaration//GEN-END:variables

}
